apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-mnist-cd-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-mnist-cd
        env: dev
    spec:
      containers:
      - name: tf-mnist-cd
        image: vykozlov/tf-mnist-cd:1.5.0-gpu
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting N GPUs
        #command: ["python","mnist_deep.py","--mnist_steps=5000"]
        command: ["./run_jupyter.sh", "--allow-root"]
