FROM tensorflow/tensorflow:1.7.0

LABEL maintainer="Valentin Kozlov <valentin.kozlov@kit.edu>"
# Dockerfile based on the one for Tensorflow from Tensorflow:
# https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
# modified by Valentin Kozlov on 2-July-2018

RUN apt-get update && \ 
    apt-get install -y --no-install-recommends git wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
# python
    pip --no-cache-dir install \
        keras \
        pylint \
        && \
    python -m ipykernel.kernelspec && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set the working directory
WORKDIR /home/tf-mnist-cd-example

# Script to run pylint
COPY ../tf-mnist-cd-example/tests/run_pylint.sh /home/tf-mnist-cd-example

# Copy the current directory contents into the container at /home
ADD ../ /home
