kind: Service
apiVersion: v1
metadata:
  name: "tf-mnist-cd-svc"
spec:
  selector:
    app: "tf-mnist-cd"
    env: production
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
      nodePort: 30888
  type: NodePort
