kind: Service
apiVersion: v1
metadata:
  name: "tf-mnist-cd-dev-svc"
spec:
  selector:
    app: "tf-mnist-cd"
    env: dev
  ports:
    - protocol: "TCP"
      port: 8890
      targetPort: 8888
      nodePort: 30890
  type: NodePort
